In [187]:
import numpy as np

def LevenshteinDistanceAllignment(w1,w2):
    l1 = len(w1)
    l2 = len(w2)
    
    table = np.zeros((l1+1,l2+1))
    backtrace_table = np.zeros((l1+1,l2+1))
    
    
    #başlangıçta=> word1: D=2  ,  word2:I=1 ataması yap. Note that: S = 3
    for i in range(table.shape[1]):#word2
        table[0][i] = i
        backtrace_table[0][i] = 1 #automatic insertion
    for i in range(table.shape[0]):#word1
        table[i][0] = i
        backtrace_table[i][0] = 2 #automatic deletion
        
    backtrace_table[0][0] = 0 
        
        
    for i in range(1,table.shape[0]):  
        for j in range(1,table.shape[1]):
            
            if (w2[j-1] == w1[i-1]):
                table[i][j] = int(table[i-1][j-1])
                backtrace_table[i][j] = 3
                
            else:
                table[i][j] = int(min(table[i-1][j]+1,table[i][j-1]+1, table[i-1][j-1]+2)) #D, I, S
                
                
                if table[i-1][j]+1 == table[i][j-1]+1 == table[i-1][j-1]+2: # üçü de eşit ise subs olur => 3
                    backtrace_table[i][j] = 3
                
                else:# üçü de eşit değil ise
                    arg_id = np.argmin([table[i-1][j]+1,table[i][j-1]+1, table[i-1][j-1]+2])
                    
                    if arg_id == 0:
                        backtrace_table[i][j] = 2
                    if arg_id == 1:
                        backtrace_table[i][j] = 1
                    if arg_id == 2:
                        backtrace_table[i][j] = 3

    distance = int(table[-1][-1])
    distance_table = table
    
    
    
    print("Distance Table: \n",table)
    print("MED:",distance)
    print("Backtrace Table (Insertion Coded: 1 (go left) , Deletion Coded : 2 (go up), Substitution or Correct: 3 (go cross up) ): \n",backtrace_table)
    
    pointer_w1 = int(backtrace_table.shape[0]-1)
    pointer_w2 = int(backtrace_table.shape[1]-1)
    allignedW1 = ""
    
    while(True):
        
        value = backtrace_table[pointer_w1][pointer_w2]
        
        if value == 0:
            allignedW1 = allignedW1[::-1]
            break
        
        if value==1:
            allignedW1 = allignedW1 + "_"
            pointer_w2 = pointer_w2 - 1
        if value==2:
            allignedW1 = allignedW1 + w1[pointer_w1-1]
            pointer_w1 = pointer_w1 - 1
        if value==3:
            allignedW1 = allignedW1 + w1[pointer_w1-1]
            pointer_w1 = pointer_w1 - 1
            pointer_w2 = pointer_w2 - 1
            
    print("Alligned word1 is: ", allignedW1)
    

    pointer_w1 = int(backtrace_table.shape[0]-1)
    pointer_w2 = int(backtrace_table.shape[1]-1)
    allignedW2 = ""
    
    while(True):
        
        value = backtrace_table[pointer_w1][pointer_w2]
        
        if value == 0:
            allignedW2 = allignedW2[::-1]
            break
        
        if value==1:
            allignedW2 = allignedW2 + w2[pointer_w2-1]
            pointer_w2 = pointer_w2 - 1
        if value==2:
            allignedW2 = allignedW2 + "_"
            pointer_w1 = pointer_w1 - 1
        if value==3:
            allignedW2 = allignedW2 + w2[pointer_w2-1]
            pointer_w1 = pointer_w1 - 1
            pointer_w2 = pointer_w2 - 1
            
    print("Alligned word2 is: ", allignedW2)
            
        
        
    
    return distance, distance_table, backtrace_table
    
distance, distance_table, backtrace_table = LevenshteinDistanceAllignment("INTENTION","EXECUTION")

Distance Table: 
 [[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [ 1.  2.  3.  4.  5.  6.  7.  6.  7.  8.]
 [ 2.  3.  4.  5.  6.  7.  8.  7.  8.  7.]
 [ 3.  4.  5.  6.  7.  8.  7.  8.  9.  8.]
 [ 4.  3.  4.  5.  6.  7.  8.  9. 10.  9.]
 [ 5.  4.  5.  6.  7.  8.  9. 10. 11. 10.]
 [ 6.  5.  6.  7.  8.  9.  8.  9. 10. 11.]
 [ 7.  6.  7.  8.  9. 10.  9.  8.  9. 10.]
 [ 8.  7.  8.  9. 10. 11. 10.  9.  8.  9.]
 [ 9.  8.  9. 10. 11. 12. 11. 10.  9.  8.]]
MED: 8
Backtrace Table (Insertion Coded: 1 (go left) , Deletion Coded : 2 (go up), Substitution or Correct: 3 (go cross up) ): 
 [[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 3. 3. 3. 3. 3. 3. 3. 1. 1.]
 [2. 3. 3. 3. 3. 3. 3. 2. 3. 3.]
 [2. 3. 3. 3. 3. 3. 3. 2. 3. 2.]
 [2. 3. 1. 3. 1. 1. 2. 3. 3. 2.]
 [2. 2. 3. 3. 3. 3. 3. 3. 3. 3.]
 [2. 2. 3. 3. 3. 3. 3. 1. 1. 2.]
 [2. 2. 3. 3. 3. 3. 2. 3. 1. 1.]
 [2. 2. 3. 3. 3. 3. 2. 2. 3. 1.]
 [2. 2. 3. 3. 3. 3. 2. 2. 2. 3.]]
Alligned word1 is:  INTE_NTION
Alligned word2 is:  _EXECUTION
